export const products = [
  {
    id: 1,
    name: "كريم مرطب بزيت الأرغان",
    description: "ترطيب عميق يدوم 24 ساعة",
    longDescription: "كريم مرطب فاخر مصنوع من زيت الأرغان الجزائري الأصيل. يمنح بشرتك ترطيباً عميقاً يدوم 24 ساعة كاملة، مع تغذية عميقة للخلايا وحماية من الجفاف في المناخ الجزائري الحار.",
    price: 2500,
    originalPrice: 3200,
    rating: 4.9,
    reviews: 156,
    badge: "الأكثر مبيعاً",
    color: "bg-rose-100",
    image: "/products/product-1.jpg",
    beforeAfterImage: "/results/result-1.jpg",
    results: "ترطيب ملحوظ خلال 3 أيام",
  },
  {
    id: 2,
    name: "سيروم فيتامين C",
    description: "توحيد لون البشرة وإشراقها",
    longDescription: "سيروم مركّز بفيتامين C الطبيعي المستخلص من الحمضيات الجزائرية. يعمل على توحيد لون البشرة وتفتيح التصبغات وإضفاء إشراقة صحية تدوم طوال اليوم.",
    price: 3200,
    originalPrice: 4000,
    rating: 4.8,
    reviews: 203,
    badge: "جديد",
    color: "bg-amber-100",
    image: "/products/product-2.jpg",
    beforeAfterImage: "/results/result-2.jpg",
    results: "بشرة مشرقة خلال أسبوع",
  },
  {
    id: 3,
    name: "غسول وجه بالعسل الطبيعي",
    description: "تنظيف عميق بدون جفاف",
    longDescription: "غسول لطيف مصنوع من العسل الطبيعي الجزائري. ينظف بشرتك بعمق من الأوساخ والزيوت الزائدة دون أن يسبب الجفاف أو التهيج، مناسب لكل أنواع البشرة.",
    price: 1800,
    originalPrice: 2200,
    rating: 4.7,
    reviews: 89,
    badge: null,
    color: "bg-orange-100",
    image: "/products/product-3.jpg",
    beforeAfterImage: "/results/result-3.jpg",
    results: "بشرة نظيفة وناعمة من أول استخدام",
  },
  {
    id: 4,
    name: "ماسك الطين المغربي",
    description: "تنقية المسام وإزالة السموم",
    longDescription: "ماسك طيني فاخر مصنوع من الطين المغربي الأصيل. ينظف المسام بعمق ويزيل السموم والشوائب المتراكمة، ويمنح بشرتك نعومة ونضارة استثنائية بعد كل استخدام.",
    price: 2800,
    originalPrice: 3500,
    rating: 4.9,
    reviews: 178,
    badge: "عرض خاص",
    color: "bg-emerald-100",
    image: "/product-4.jpg",
    beforeAfterImage: "/results/result-4.jpg",
    results: "مسام أصغر خلال أسبوعين",
  },
  {
    id: 5,
    name: "زيت أرغان جزائري نقي",
    description: "للوجه والشعر - عضوي 100%",
    longDescription: "زيت أرغان 100% طبيعي وعضوي مستخلص من لوز الأرغان الجزائري. يغذي البشرة والشعر بعمق، ويمنح نعومة وبريقاً استثنائياً مع الاستخدام المنتظم.",
    price: 3500,
    originalPrice: 4200,
    rating: 5.0,
    reviews: 234,
    badge: "الأفضل تقييماً",
    color: "bg-yellow-100",
    image: "/products/product-5.jpg",
    beforeAfterImage: "/results/result-5.jpg",
    results: "نعومة ملحوظة من أول استخدام",
  },
  {
    id: 6,
    name: "كريم مكافحة التصبغات",
    description: "نتائج ملحوظة خلال أسبوعين",
    longDescription: "كريم متخصص لعلاج التصبغات وتوحيد لون البشرة. يحتوي على مكونات طبيعية فعّالة مثبتة علمياً تعمل على تفتيح البقع الداكنة وإعادة الإشراقة الطبيعية للبشرة.",
    price: 4200,
    originalPrice: 5000,
    rating: 4.8,
    reviews: 145,
    badge: null,
    color: "bg-pink-100",
    image: "/products/product-6.jpg",
    beforeAfterImage: "/results/result-6.jpg",
    results: "تصبغات أخف خلال أسبوعين",
  },
]
